name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [webkit] # WebKit is used for "Mobile Safari" tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install pnpm
        env:
          SHELL: "/bin/bash"  # Define explicitly the shell
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          echo "PNPM_HOME=$PNPM_HOME" >> $GITHUB_ENV
          echo "PATH=$PNPM_HOME:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm playwright test --project="Mobile Safari"  

